# Generated by Django 4.0.4 on 2022-04-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='datOfJoining',
            new_name='DatOfJoining',
        ),
    ]
