# Generated by Django 4.0.4 on 2022-04-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_datofjoining_employee_datofjoining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PhotoFielName',
            new_name='PhotoFieldName',
        ),
    ]
