# Generated by Django 4.0.4 on 2022-04-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_rename_photofielname_employee_photofieldname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PhotoFieldName',
            new_name='PhotoFileName',
        ),
    ]
