# Generated by Django 4.0.4 on 2022-04-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_rename_photofieldname_employee_photofilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DatOfJoining',
            new_name='DateOfJoining',
        ),
    ]
